### ISSUE TITLE
Provide a way to weight random sounds

### ISSUE THREAD

**Issue by LarryBoi** [piecesofcodecom/soundscape-adventure#15]
This module is a fantastic foundation, but currently, as far as I can tell, there is no way to _weight_ random sounds. I am currently finding that the random sounds I want to play play far too often. My current use-case is that of playing monster sounds in the distance - I want these to play, ideally, maybe once every thirty seconds, to imply that there is danger deeper in the level my players are exploring, but they haven't quite reached it yet. As things are, though, the sounds are playing almost constantly, and there's no way to change that.

Even just a simple 4-state toggle for each random sound would be useful, something like 'very rarely, rarely, sometimes, often' (perhaps translating to once every 2 minutes on average, once every minute on average, once every 20 seconds on average, once every 5 seconds on average, respectively. Another option could be a similar implementation to an older soundscape add-on I used (now deprecated I believed), which had a 'minimum time before this track repeats' and 'maximum time before this track repeats.' Maybe this could be configurable in settings?) 

No matter the implementation, this would be a game changer, and it's the lack of this feature that I think is what prevents this add-on from being a completely viable option at this stage.

**Comment by mrcomac** [comment]
Hi @LarryBoi ,

Thank you for your feedback. I'm glad that you're enjoying it despite the lack of functionalities, and I agree with you that we are missing some stuffs. The Soundscape Adventure still have some gaps that i want to fill based on the requests of the users. That was the reason I've launched it, to get feedback to prioritise features.

I'm glad that I have many issues to work on, instead of working on things that i think would be the right feature.

There is a issue similar to yours request https://github.com/piecesofcodecom/soundscape-adventure/issues/8, and I already started working on it. The way that i'm thinking this interval configuration is to add a slider that you can select the interval for each sound and group of sounds. You will be able to select by moving the thumbs on the slider or editing the Min and Max in the boxes.

![image](https://github.com/user-attachments/assets/a0ef644d-a557-4bea-848b-4ce120eae983)

Based on your request, around 2minutes, i already know that i need to increase the width for those boxes to support numbers with 3 digits.

Please feel free to coment and give your opinion on this next feature that i'm planning to relase soon.

**Comment by brunocalado** [comment]
It's related to https://github.com/piecesofcodecom/soundscape-adventure/issues/8

**Comment by LarryBoi** [comment]
> Hi @LarryBoi ,
> 
> Thank you for your feedback. I'm glad that you're enjoying it despite the lack of functionalities, and I agree with you that we are missing some stuffs. The Soundscape Adventure still have some gaps that i want to fill based on the requests of the users. That was the reason I've launched it, to get feedback to prioritise features.
> 
> I'm glad that I have many issues to work on, instead of working on things that i think would be the right feature.
> 
> There is a issue similar to yours request #8, and I already started working on it. The way that i'm thinking this interval configuration is to add a slider that you can select the interval for each sound and group of sounds. You will be able to select by moving the thumbs on the slider or editing the Min and Max in the boxes.
> 
> ![image](https://private-user-images.githubusercontent.com/6748594/356367200-a0ef644d-a557-4bea-848b-4ce120eae983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODkxNDAsIm5iZiI6MTcyMzE4ODg0MCwicGF0aCI6Ii82NzQ4NTk0LzM1NjM2NzIwMC1hMGVmNjQ0ZC1hNTU3LTRiZWEtODQ4Yi00Y2UxMjBlYWU5ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMDczNDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIxYWU2Mjk3YjRmZmY2MGUxMDFhOTQyMThiYzlkMmNmZTY3N2MyYzVjYzZhYTAzM2U3NzJkM2E3OGJjYWFkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AL8O0u1Hf90Z-4sqKA6kHIz5qMQjw7AsvsP203SIMaU)
> 
> Based on your request, around 2minutes, i already know that i need to increase the width for those boxes to support numbers with 3 digits.
> 
> Please feel free to coment and give your opinion on this next feature that i'm planning to relase soon.

Apologies, I missed that issue! This looks like a great implementation, though, and it's much more intuitive than what I recommended. But yes, glad you're looking to extend the options a little to at least a couple of minutes.

Can't wait to see how this develops.

**Comment by mrcomac** [comment]
This should be available in V0.1.2
