### ISSUE TITLE
Bug - New soundscape option includes duplicate options

### ISSUE THREAD

**Issue by LarryBoi** [piecesofcodecom/soundscape-adventure#19]
I only have one instance of 'Soundscape-Underground' as a folder, yet when I go to create a new Soundscape, it shows the option twice.

This is with v0.1.2

![Duplicate](https://github.com/user-attachments/assets/5c41ced8-8a30-43d7-b622-f3aac0d1186b)

**Comment by mrcomac** [comment]
Hi @LarryBoi,

I noticed this behavior on my server after launch the version, which is odd because it doesn't happen on my local instance.

Meanwhile I'm investigating the issue, a current workaround is to create all the required folders within the soundscape folder (Ambience, Loop, Random, and Soundpad).

Soundpad is a new sound category that allows you to play a sound whenever you want, regardless of whether a mood is currently playing or not.
