### ISSUE TITLE
Random Control

### ISSUE THREAD

**Issue by brunocalado** [piecesofcodecom/soundscape-adventure#8]
Hi. Can you add a way to control the timing of random sounds?

Maybe a way to set each sound the random interval.

**Comment by mrcomac** [comment]
Hi @brunocalado,
the way that i'm planning to implement this is provinding a slider that you can select the interval for a specific sound or group of sounds.

![image](https://github.com/user-attachments/assets/a0ef644d-a557-4bea-848b-4ce120eae983)

As you can see in the image above, there will be 2 boxes with the min and max values that you also can edit, instead of moving the slider.

Please let me know if that solution works for you.

**Comment by brunocalado** [comment]
Very nice. But, just the textbox would be enough and less confusing.

**Comment by LarryBoi** [comment]
> Very nice. But, just the textbox would be enough and less confusing.

I would disagree, honestly. I think a slider is a pretty intuitive implementation.

**Comment by brunocalado** [comment]
> > Very nice. But, just the textbox would be enough and less confusing.
> 
> I would disagree, honestly. I think a slider is a pretty intuitive implementation.

But, you need the textbox to change the slider. The slider use the value in the textbox.

**Comment by mrcomac** [comment]
@brunocalado @LarryBoi

it seems sounds will have a list of features.
![image](https://github.com/user-attachments/assets/740b14fb-890a-4482-b61c-82d1695b56a8)

I'll keep like in the example above, but i already know that i need to rework the css and html to have a better visualisation of the options for each sound.

**Comment by mrcomac** [comment]
This should be available in V0.1.2
